sonar.projectKey=aotalvaros_cyberguard-system_frontend
sonar.organization=aotalvaros
sonar.projectName=cyberguard-system-frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/cyberguard-system-app/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**
